headers = []

[functions]

[functions.__api]
included_files = ["/Users/eduardoboucas/Sites/tests/gatsby-test/my-gatsby-site/.cache/functions/**"]
external_node_modules = ["msgpackr-extract"]

[functions.__dsg]
included_files = ["public/404.html", "public/500.html", "/Users/eduardoboucas/Sites/tests/gatsby-test/my-gatsby-site/.cache/query-engine/**", "/Users/eduardoboucas/Sites/tests/gatsby-test/my-gatsby-site/.cache/page-ssr/**", "!**/*.js.map", "/Users/eduardoboucas/Sites/tests/gatsby-test/my-gatsby-site/.cache/data/**"]
external_node_modules = ["msgpackr-extract"]
node_bundler = "esbuild"

[functions.__ssr]
included_files = ["public/404.html", "public/500.html", "/Users/eduardoboucas/Sites/tests/gatsby-test/my-gatsby-site/.cache/query-engine/**", "/Users/eduardoboucas/Sites/tests/gatsby-test/my-gatsby-site/.cache/page-ssr/**", "!**/*.js.map", "/Users/eduardoboucas/Sites/tests/gatsby-test/my-gatsby-site/.cache/data/**"]
external_node_modules = ["msgpackr-extract"]
node_bundler = "esbuild"

[functions."*"]

[[plugins]]
package = "@netlify/plugin-gatsby"
origin = "config"

[plugins.inputs]

[build]
publish = "/Users/eduardoboucas/Sites/tests/gatsby-test/my-gatsby-site/public"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/__api"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]